# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: munin2graphite 0.2.3 ruby lib

Gem::Specification.new do |s|
  s.name = "munin2graphite"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jose Fernandez (magec)"]
  s.date = "2017-01-23"
  s.description = "This gem will install as a daemon and can be used to connect to a graphite and a carbon backend. It will not only post the data for the metrics but also create graphs into graphite, by means of a translation from munin-node."
  s.email = "jfernandezperez@gmail.com"
  s.executables = ["munin2gdash", "munin2graphite", "munin2graphite-1r", "munin2graphite-daemon"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "bin/munin2gdash",
    "bin/munin2graphite",
    "bin/munin2graphite-1r",
    "bin/munin2graphite-daemon",
    "conf/munin2graphite.conf.example",
    "etc/munin2graphite/munin2graphite.conf.example",
    "lib/ast_node.rb",
    "lib/carbon.rb",
    "lib/graphite.rb",
    "lib/graphite/base.rb",
    "lib/graphite/graph.rb",
    "lib/graphite/metric.rb",
    "lib/graphite/my_graph.rb",
    "lib/graphite/user_graph.rb",
    "lib/munin2graphite.rb",
    "lib/munin2graphite/config.rb",
    "lib/munin2graphite/scheduler.rb",
    "lib/munin_graph.rb",
    "munin2graphite.gemspec",
    "test/munin2graphite/config_test.rb",
    "test/test_config.rb",
    "test/test_graphite.rb",
    "test/test_init.rb",
    "test/test_munin.rb",
    "test/test_munin_graph.rb",
    "test/test_my_graph.rb",
    "test/test_scheduler.rb"
  ]
  s.homepage = "http://github.com/magec/munin2graphite"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5"
  s.summary = "Allows to post both data and graphic info from munin to graphite (https://launchpad.net/graphite)"

  s.add_runtime_dependency('rufus-scheduler', "= 2.0.10")
  s.add_runtime_dependency('daemons', "= 1.1.4")
  s.add_runtime_dependency('parseconfig', ">= 0")
  s.add_runtime_dependency('munin-ruby', "~> 0.2.5")
  s.add_runtime_dependency('json', "~> 1.8.2")
  s.add_runtime_dependency('diplomat', ">= 2.0.2")
  s.add_development_dependency('jeweler', "~> 1.8.4")
end
