--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Import data from the config to our config object.
full_name: ParseConfig#import_config
is_singleton: false
name: import_config
params: ()
visibility: public
