--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Daemons::ApplicationGroup#find_applications_by_pidfiles
is_singleton: false
name: find_applications_by_pidfiles
params: (dir)
visibility: public
