--- !ruby/object:RI::ClassDescription 
attributes: 
- !ruby/object:RI::Attribute 
  comment: 
  name: app_argv
  rw: RW
- !ruby/object:RI::Attribute 
  comment: 
  name: app_name
  rw: R
- !ruby/object:RI::Attribute 
  comment: 
  name: applications
  rw: R
- !ruby/object:RI::Attribute 
  comment: 
  name: controller_argv
  rw: RW
- !ruby/object:RI::Attribute 
  comment: 
  name: dir
  rw: RW
- !ruby/object:RI::Attribute 
  comment: 
  name: dir_mode
  rw: RW
- !ruby/object:RI::Attribute 
  comment: 
  name: monitor
  rw: R
- !ruby/object:RI::Attribute 
  comment: 
  - !ruby/struct:SM::Flow::P 
    body: true if the application is supposed to run in multiple instances
  name: multiple
  rw: R
- !ruby/object:RI::Attribute 
  comment: 
  - !ruby/struct:SM::Flow::P 
    body: attr_reader :controller
  name: options
  rw: R
- !ruby/object:RI::Attribute 
  comment: 
  name: script
  rw: R
class_methods: 
- !ruby/object:RI::MethodSummary 
  name: new
comment: 
constants: []

full_name: Daemons::ApplicationGroup
includes: []

instance_methods: 
- !ruby/object:RI::MethodSummary 
  name: create_monitor
- !ruby/object:RI::MethodSummary 
  name: find_applications
- !ruby/object:RI::MethodSummary 
  name: find_applications_by_app_name
- !ruby/object:RI::MethodSummary 
  name: find_applications_by_pidfiles
- !ruby/object:RI::MethodSummary 
  name: new_application
- !ruby/object:RI::MethodSummary 
  name: pidfile_dir
- !ruby/object:RI::MethodSummary 
  name: reload_all
- !ruby/object:RI::MethodSummary 
  name: setup
- !ruby/object:RI::MethodSummary 
  name: show_status
- !ruby/object:RI::MethodSummary 
  name: start_all
- !ruby/object:RI::MethodSummary 
  name: stop_all
- !ruby/object:RI::MethodSummary 
  name: zap_all
name: ApplicationGroup
superclass: Object
