--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Daemons::ApplicationGroup#find_applications
is_singleton: false
name: find_applications
params: (dir)
visibility: public
