--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Daemons::ApplicationGroup#new_application
is_singleton: false
name: new_application
params: (add_options = {})
visibility: public
