--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Parse 'config' request
full_name: Munin::Parser#parse_config
is_singleton: false
name: parse_config
params: (data)
visibility: public
