--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Parse configuration arguments
full_name: Munin::Parser#parse_config_args
is_singleton: false
name: parse_config_args
params: (args)
visibility: public
