--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Get a configuration information for service
- !ruby/struct:SM::Flow::P 
  body: services - Name of the service, or list of service names
full_name: Munin::Node#config
is_singleton: false
name: config
params: (services, raw=false)
visibility: public
